---

- name: Clone CLAW Alpaca
  git:
    repo: https://github.com/Islandora/Alpaca.git
    dest: "{{ alpaca_clone_directory }}"
    version: "{{ alpaca_version }}"
  register: alpaca_git

- name: Change directory permissions
  file:
    path: "{{ alpaca_clone_directory }}"
    state: directory
    owner: "{{ alpaca_user }}"
    group: "{{ alpaca_group }}"
    recurse: yes

- name: Install Alpaca via Gradle
  become: yes
  become_user: "{{ alpaca_user }}"
  command: ./gradlew build shadowJar
  args:
    chdir: "{{ alpaca_clone_directory }}"
  when: alpaca_git.changed

