fcrepo_version: 6.0.0
fcrepo_user: "{{ tomcat9_server_user }}"
fcrepo_war_path: "{{ tomcat9_home }}/webapps/fcrepo.war"
fcrepo_home_dir: /opt/fcrepo
fcrepo_data_dir: "{{ tomcat9_home }}/fcrepo-data"
fcrepo_activemq_template: activemq.xml.j2
fcrepo_activemq_broker_url: "tcp://localhost:61616"
fcrepo_config_dir: "{{ fcrepo_home_dir }}/configs"
fcrepo_config_file: "{{ fcrepo_config_dir }}/fcrepo.properties"

# For Fedora 5, for production use either "jdbc-mysql" or "jdbc-postgresql"
fcrepo_persistence: file-simple
fcrepo_binary_directory: "{{ fcrepo_data_dir}}/binaries"
fcrepo_object_directory: "{{ fcrepo_data_dir}}/objects"

# Database type for caching/indexes in Fedora 6.
# Use either "mysql" or "postgresql"
fcrepo_db_type: mysql

# Used for database connection. Please change the password locally!
fcrepo_db_name: fcrepo
fcrepo_db_user: fcrepo
fcrepo_db_password: fcrepo
fcrepo_db_host: "127.0.0.1"
fcrepo_db_port: "3306"
# user that has database create and user add privs.
fcrepo_db_root_user: "root"
fcrepo_db_root_password: "islandora"

# External content paths can be directories or urls,
# and they MUST end in /
fcrepo_allowed_external_content:
  - http://localhost:8000/

fcrepo_allowed_external_content_file: "{{ fcrepo_config_dir }}/allowed-external-content.txt"

# Additional RDF Namespace/prefix mappings can be added here, please review the existing mappings first.
# These need to be strings to get parsed in to the resulting Yaml file correctly.
fcrepo_namespace_mappings:
  - "pcdm: http://pcdm.org/models#"
  - "pcdmfmt: http://pcdm.org/file-format-types#"
  - "pcdmrts: http://pcdm.org/rights#"
  - "pcdmuse: http://pcdm.org/use#"
  - "pcdmwrks: http://pcdm.org/works#"

fcrepo_auth_header_name:
