---
# locally run aws_provision.yml
# locally run ansible-galaxy install -r requirements.yml
# locally run ansible-playbook -i inventory/aws playbook.yml -e "islandora_distro=ubuntu/xenial64" -e @inventory/aws/group_vars/all/passwords.yml
- hosts: localhost #boto takes care of this?
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.medium
    security_group: DEV-ASU-ALL
    image: ami-06d51e91cea0dac8d
    keypair: Islandora-Dev
    region: us-west-2
    count: 1
  vars_files:
    - aws_keys.yml
  tasks:
    - name: provision ec2
      ec2:
        key_name: "{{ keypair }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_access_key: "{{ aws_access_key }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        count: "{{ count }}"
        vpc_subnet_id: subnet-0a175a933a579e7ea
        assign_public_ip: yes
        instance_tags:
          repository_purpose: tomcat
          Name: Islandora Dev-Tomcat
        volumes:
          - device_name: /dev/sda1
            volume_size: 8
            delete_on_termination: true
      register: ec2
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        state: started
      with_items: "{{ ec2.instances }}"
# note that right now that it makes an unnamed 50GB volume by default
