---

- hosts: crayfish
  become: yes

  roles:
    - name: geerlingguy.repo-remi
      when: ansible_os_family == "RedHat"
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.git
    - geerlingguy.composer
    - Islandora-Devops.crayfish
