# locally run ansible-playbook rds_provision.yml
- hosts: localhost #boto takes care of this?
  connection: local
  gather_facts: False
  vars:
    security_group: DEV-ASU-ALL
    image: ami-06d51e91cea0dac8d
    keypair: Islandora-Dev
    region: us-west-2
    count: 1
  vars_files:
    - aws_keys.yml
    - inventory/aws/group_vars/all/passwords.yml
  tasks:
    - name: create RDS
      rds:
        command: create
        instance_name: islandora-drupal
        db_engine: MySQL
        size: 10
        instance_type: db.t2.micro
        username: drupal8
        db_name: drupal8
        password: "{{ drupal_db_password }}"
        vpc_security_groups: sg-025cd95ef40eefa4c
        aws_secret_key: "{{ aws_secret_key }}"
        aws_access_key: "{{ aws_access_key }}"
        region: "{{ region }}"
        subnet: libdev-db-private-ips
        tags:
          Application: islandora
