---

- hosts: solr
  become: yes

  roles:
    - role: java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk
    - role: java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
    - solr
