---

- hosts: webserver
  become: yes

  vars:
    php_version: "7.4"

  environment:
    COMPOSER_MEMORY_LIMIT: -1

  roles:
    - name: geerlingguy.repo-remi
      when: ansible_os_family == "RedHat"
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.git
    - geerlingguy.composer
    - symlink
    - geerlingguy.drush
    - geerlingguy.drupal
    - perms-fix
    - Islandora-Devops.drupal-openseadragon
    - webserver-app
    - Islandora-Devops.riprap
    - Islandora-Devops.bagger
    - Islandora-Devops.matomo
    # - Islandora-Devops.fits

  tasks:
    - name: ensure ssl directory
      file: path=/etc/ssl/private state=directory

    # - name: copy ssl cer and key
    #   copy: src={{ item }} dest=/etc/ssl/private owner=root group=root mode=400
    #   with_items:
    #     - __lib_asu_edu.key
    #     - __lib_asu_edu.cer
    - name: Download Islandora FITS
      composer:
        command: require
        arguments: islandora-rdm/islandora_fits
        working_dir: "{{ drupal_core_path }}/.."
    - name: Enable Islansdora FITS
      command: "{{ drush_path }} --root {{ drupal_core_path }} -y en islandora_fits"