# ---
# - name: make sure islandora directory exists
#   file:
#     path: /home/ubuntu/islandora
#     state: directory
#     owner: ubuntu
#     group: www-data
#   become_user: ubuntu
# # - name: clone claw-app into /home/ubuntu/islandora/claw-app
# #   git:
# #     repo: 'https://github.com/asulibraries/islandora-repo'
# #     dest: /home/ubuntu/islandora/claw-app
# #   become_user: ubuntu
# - name: symlink local claw-sandbox folder to drupal root
#   file:
#     src: /home/ubuntu/islandora/claw-app
#     dest: /var/www/html/drupal
#     state: link
#     force: yes

- name: make the drupal root
  file:
    path: /var/www/html/drupal
    state: directory
    mode: 0775
    owner: "{{webserver_app_user}}"
    group: "{{webserver_app_user}}"
    force: no
  become: true
  ignore_errors: yes

- name: check if rules file exists
  stat:
    path: /var/www/html/drupal/web
  register: drupal_exists

- name: clone the ASU project
  git:
    repo: 'https://github.com/asulibraries/islandora-repo'
    dest: /var/www/html/drupal
  when: drupal_exists.stat.exists == False


- name: change composer permissions
  file:
    path: /var/www/html/drupal/composer.json
    mode: 0777
- name: change composer permissions
  file:
    path: /var/www/html/drupal/composer.lock
    mode: 0777

- name: change drupal root permissions
  file:
    path: /var/www/html/drupal
    state: directory
    recurse: yes
    owner: "{{ drupal_owner }}"
    group: "{{ drupal_group }}"
    # owner: "{{webserver_app_user}}"
    # group: "{{webserver_app_user}}"

- name: change vendor permissions
  file:
    path: /var/www/html/drupal/vendor
    state: directory
    recurse: yes
    mode: 0775
    owner: "{{ drupal_owner }}"
    group: "{{ drupal_group }}"
    # owner: "{{webserver_app_user}}"
    # group: "{{webserver_app_user}}"
- name: Run composer install if composer.json
  composer:
    command: install
    working_dir: /var/www/html/drupal
#   become_user: "{{webserver_app_user}}"
  become_user: "{{ drupal_owner }}"
- name: make sure we have islandora and up to date
  composer:
    command: update
    arguments: islandora/islandora
    working_dir: /var/www/html/drupal
#   become_user: "{{webserver_app_user}}"
  become_user: "{{ drupal_owner }}"

- name: make sure we have controlled_access_terms and up to date
  composer:
    command: update
    arguments: islandora/controlled_access_terms
    working_dir: /var/www/html/drupal
#   become_user: "{{webserver_app_user}}"
  become_user: "{{ drupal_owner }}"

- name: make private files directory
  file:
    path: "{{ drupal_private_dir }}"
    state: directory
    owner: "{{webserver_app_user}}"
    group: "{{webserver_app_user}}"
    mode: 0775
# TODO change the settings.php file to reflect

# Clone the non-composer modules

- name: clone ASU fork of islandora_bagger_integration
  git:
    dest: "{{drupal_core_path}}/modules/custom/islandora_bagger_integration"
    repo: https://github.com/asulibraries/islandora_bagger_integration.git
    clone: yes
    update: yes
    version: bag_node_action

- name: clone ASU fork of persistent identifiers
  git:
    dest: "{{drupal_core_path}}/modules/contrib/persistent_identifiers"
    repo: https://github.com/asulibraries/persistent_identifiers.git
    clone: yes
    update: yes
    version: master

- name: enable persistent_identifiers
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y pm-enable persistent_identifiers"

- name: enable hdl
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y pm-enable hdl"
