---

drupal_build_composer_project: true
drupal_composer_install_dir: /var/www/html/drupal
drupal_core_owner: "{{ ansible_user }}"
drupal_composer_dependencies:
  - "zaporylie/composer-drupal-optimizations:^1.1" 
  - "drupal/devel:^4.0"
  - "drupal/core-dev:^9.2"
  - "drush/drush:^10.3"
  - "drupal/rdfui:^1.0-beta1"
  - "drupal/restui"
  - "drupal/search_api_solr"
  - "drupal/content_browser:^1.0@alpha"
  - "drupal/matomo:^1.7"
  - "drupal/pdf:1.x-dev"
  - "drupal/features"
  - "drupal/admin_toolbar"
  - "drupal/rest_oai_pmh"
  - "drupal/transliterate_filenames"
  - "easyrdf/easyrdf"
  - "drupal/context:^4.0@beta"
  - "--with-all-dependencies islandora/islandora_defaults:^2 islandora/openseadragon:^2 islandora/controlled_access_terms:^2 drupal/archivesspace:1.x-dev@dev islandora/islandora:^2"
  - "islandora-rdm/islandora_fits"
  - "drupal/diff"
  - "drupal/rrssb"
  - "drupal/webform"
  - "drupal/workbench"
  - "drupal/schema_metatag"
  - "drupal/address"
  - "drupal/title_length"
  - "drupal/migrate_run"
  - "drupal/weight"
  - "drupal/superfish"
  # https://github.com/roblib/lc_subject_field
  # https://github.com/UNLV-Libraries/archivesspace-drupal
  # https://github.com/mjordan/islandora_workbench
  - "drupal/simple_sitemap"
  - "drupal/auto_entitylabel"
  - "drupal/migrate_file"
  - "drupal/group"
  - "drupal/smtp"
  - "drupal/redirect"
  - "drupal/pathauto"
  - "drupal/s3fs"
  - "drupal/s3fs_cors"
  - "drupal/cdn"
drupal_composer_project_package: "drupal/recommended-project:^9.2"
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"
drupal_core_path: "{{ drupal_composer_install_dir }}/web"
drupal_db_user: drupal8
drupal_db_name: drupal8
drupal_db_backend: "{{ claw_db }}"
drupal_db_host: "islandora-drupal.cnsoayetwjju.us-west-2.rds.amazonaws.com"
drupal_domain: "claw.dev"
drupal_site_name: "Islandora 8"
drupal_install_profile: standard
drupal_account_name: admin
drupal_deploy_dir: "{{ drupal_composer_install_dir }}"
drupal_enable_modules:
  - rdf
  - responsive_image
  - syslog
  - serialization
  - basic_auth
  - rest
  - simpletest
  - restui
  - devel
  - search_api_solr
  - facets
  - content_browser
  - matomo
  - pdf
  - admin_toolbar
  - clamav
  - features
  - admin_toolbar_tools
  - islandora_core_feature
  - islandora_text_extraction
  - islandora_text_extraction_defaults
  - transliterate_filenames
  - islandora_defaults
  - controlled_access_terms_defaults
  - islandora_defaults
  - islandora_fits
  - islandora_breadcrumbs
  - islandora_iiif
  - islandora_oaipmh
  - workbench
  - content_moderation
  - webform
  - schema_metatag
  - jsonapi
  - superfish
  - persistent_identifiers
  - hdl
  - simple_sitemap
  - migrate_file
  - group
  - islandora_search
  - smtp
  - deposit_agreement
  # - asu_migrate
  # - bagger_extension
  - repo_bento_search
  - asu_default_fields
drupal_trusted_hosts:
  - ^localhost$
  - "{{ hostvars[groups['webserver'][0]].ansible_host }}"
  - ^keep.lib.asu.edu$
  - ^islandora-webserver-elb-1217339900.us-west-2.elb.amazonaws.com$
  - 10.192.17.252
drupal_trusted_hosts_file: "{{ drupal_core_path }}/sites/default/settings.php"
drupal_public_filesystem: "{{ drupal_core_path }}/sites/default/files"
drupal_external_libraries_directory: "{{ drupal_core_path }}/libraries"
fedora_base_url: "http://{{ hostvars[groups['tomcat'][0]].ansible_host }}:8080/fcrepo/rest/asu_ir"
drupal_jsonld_remove_format: true
drupal_gemini_pseudo_bundles:
  - islandora_object:node
  - image:media
  - file:media
  - audio:media
  - video:media
openseadragon_composer_item: "islandora/openseadragon:dev-8.x-1.x"
