---

webserver_app: yes
openseadragon_iiiv_set_var: yes
openseadragon_iiiv_server: "http://{{ hostvars[groups['tomcat'][0]].ansible_host }}:8080/cantaloupe/iiif/2"

drupal_owner: ubuntu
drupal_group: ubuntu
php_post_max_size: "64M"
drupal_composer_project_package: "islandora/drupal-project:8.8.1"


cantaloupe_deploy_war: yes
cantaloupe_deploy_war_path: "{{ tomcat8_home }}/webapps"
cantaloupe_user: tomcat8
cantaloupe_group: tomcat8
cantaloupe_admin_enabled: "true"
cantaloupe_OpenJpegProcessor_path_to_binaries: /usr/local/bin
cantaloupe_log_application_ConsoleAppender_enabled: "false"
cantaloupe_log_application_FileAppender_enabled: "true"
cantaloupe_log_application_FileAppender_pathname: "{{ cantaloupe_log_path }}/application.log"
cantaloupe_log_access_FileAppender_enabled: "true"
cantaloupe_log_access_FileAppender_pathname: "{{ cantaloupe_log_path }}/access.log"
cantaloupe_processor_jp2: OpenJpegProcessor
cantaloupe_cache_source: FilesystemCache
cantaloupe_cache_derivative: FilesystemCache
cantaloupe_create_FilesystemCache_dir: yes
cantaloupe_resolver_static: HttpResolver
riprap_content_type: "asu_repository_item"

apache_listen_port: 80
apache_create_vhosts: true
apache_vhosts_filename: "islandora.conf"
apache_remove_default_vhost: true
apache_vhosts:
  - servername: "repo-dev.aws.lib.asu.edu"
    documentroot: "/var/www/html/drupal/web"
    allow_override: All
    options: -Indexes +FollowSymLinks
apache_mods_enabled:
  - rewrite.load
  - ssl.load
apache_vhosts_ssl:
  - servername: repo-dev.aws.lib.asu.edu
    documentroot: "/var/www/html/drupal/web"
    certificate_file: "/etc/ssl/private/__lib_asu_edu.cer"
    certificate_key_file: "/etc/ssl/private/__lib_asu_edu.key"
    extra_parameters: |
      RewriteEngine On
      RewriteCond %{HTTPS} !=on
      RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]

apache_allow_override: "All"
apache_options: "-Indexes +FollowSymLinks"

# RewriteCond %{HTTP_HOST} !^www\. [NC]
# RewriteRule ^(.*)$ http://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
    
    
