---

drupal_build_composer_project: true
drupal_composer_install_dir: /var/www/html/drupal
drupal_core_owner: "{{ ansible_user }}"
drupal_composer_dependencies:
  - "zaporylie/composer-drupal-optimizations:^1.0"
  - "drupal/console:~1.0"
  - "drupal/devel:^2.0"
  - "drupal/rdfui:^1.0-beta1"
  - "drupal/restui:^1.16"
  - "drupal/search_api_solr:^2.0"
  - "drupal/facets:^1.3"
  - "drupal/content_browser:^1.0@alpha"
  - "drupal/matomo:^1.7"
  - "drupal/pdf:1.x-dev"
  - "drupal/admin_toolbar"
  - "drupal/clamav"
  - "drupal/features"
  - "drupal/config_split"
  - "islandora/carapace:1.0.0"
  - "islandora/islandora_defaults:dev-8.x-1.x"
  - "drupal/orcid"
  - "drupal/bibcite"
drupal_composer_project_package: "islandora/drupal-project:8.7"
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"
drupal_core_path: "{{ drupal_composer_install_dir }}/web"
drupal_db_user: drupal8
drupal_db_name: drupal8
drupal_db_backend: "{{ claw_db }}"
drupal_db_host: "127.0.0.1"
drupal_domain: "claw.dev"
drupal_site_name: "Islandora 8"
drupal_install_profile: standard
drupal_account_name: admin
drupal_enable_modules:
  - rdf
  - responsive_image
  - syslog
  - serialization
  - basic_auth
  - rest
  - simpletest
  - restui
  - devel
  - search_api_solr
  - search_api_solr_defaults
  - facets
  - content_browser
  - matomo
  - pdf
  - islandora_core_feature
  - admin_toolbar
  - config_split
  - clamav
  - features
  - islandora_defaults
  - controlled_access_terms_defaults
  - orcid
  - bibcite
drupal_trusted_hosts:
  - ^localhost$
  - ^repo-dev.aws.lib.asu.edu$
  - ^35.163.77.215$
  - ^ec2-35-163-77-215.us-west-2.compute.amazonaws.com$
  - "{{ hostvars[groups['webserver'][0]].ansible_host }}"
drupal_trusted_hosts_file: "{{ drupal_core_path }}/sites/default/settings.php"
drupal_public_filesystem: "{{ drupal_core_path }}/sites/default/files"
drupal_external_libraries_directory: "{{ drupal_core_path }}/libraries"
fedora_base_url: "http://127.0.0.1:8080/fcrepo/rest/"
drupal_jsonld_remove_format: true
drupal_gemini_pseudo_bundles:
  - islandora_object:node
  - image:media
  - file:media
  - audio:media
  - video:media
openseadragon_composer_item: "islandora/openseadragon:dev-8.x-1.x"
