---

apache_listen_port: 80
apache_create_vhosts: true
apache_vhosts_filename: "islandora.conf"
apache_remove_default_vhost: true
apache_vhosts:
  - servername: "repository.lib.asu.edu"
    documentroot: "/var/www/html/drupal/web"
    allow_override: All
    options: -Indexes +FollowSymLinks
apache_mods_enabled:
  - rewrite.load
  - ssl.load
apache_vhosts_ssl:
  - servername: repository.lib.asu.edu
    documentroot: "/var/www/html/drupal/web"
    certificate_file: "/etc/ssl/private/__lib_asu_edu.cer"
    certificate_key_file: "/etc/ssl/private/__lib_asu_edu.key"
    extra_parameters: |
      RewriteEngine On
      RewriteCond %{HTTPS} !=on
      RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]

apache_allow_override: "All"
apache_options: "-Indexes +FollowSymLinks"

# RewriteCond %{HTTP_HOST} !^www\. [NC]
# RewriteRule ^(.*)$ http://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

