---

drupal_build_composer_project: true
drupal_composer_install_dir: /var/www/html/drupal
drupal_core_owner: "{{ ansible_user }}"
drupal_composer_dependencies:
  - "zaporylie/composer-drupal-optimizations:^1.0"
  - "drupal/console:~1.0"
  - "drupal/devel:^2.0"
  - "drush/drush:^9.0"
  - "drupal/rdfui:^1.0-beta1"
  - "drupal/restui:^1.16"
  - "drupal/search_api_solr:^4.1"
  - "drupal/facets:^1.3"
  - "drupal/content_browser:^1.0@alpha"
  - "drupal/matomo:^1.7"
  - "drupal/pdf:1.x-dev"
  - "drupal/clamav"
  - "drupal/features"
  - "drupal/config_split"
  - "drupal/admin_toolbar:^2.0"
  - "drupal/rest_oai_pmh:^1.0"
  - "drupal/transliterate_filenames:^1.3"
  - "islandora/carapace:dev-8.x-3.x"
  - "islandora/islandora_defaults:dev-8.x-1.x"
  - "drupal/webform"
  - "drupal/workbench"
  - "drupal/title_length"
  - "drupal/migrate_run"
  - "drupal/weight"
  - "drupal/superfish"
  - "drupal/simple_sitemap"
  - "drupal/migrate_file"
  - "drupal/smtp"
drupal_composer_project_package: "islandora/drupal-project:8.8.1"
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"
drupal_core_path: "{{ drupal_composer_install_dir }}/web"
drupal_db_user: drupal8
drupal_db_name: drupal8
drupal_db_backend: "{{ claw_db }}"
drupal_db_host: "islandora-landing-drupal.cnsoayetwjju.us-west-2.rds.amazonaws.com"
drupal_domain: "claw.dev"
drupal_site_name: "Islandora 8"
drupal_install_profile: standard
drupal_account_name: admin
drupal_deploy_dir: "{{ drupal_composer_install_dir }}"
drupal_enable_modules:
  - rdf
  - responsive_image
  - syslog
  - serialization
  - basic_auth
  - rest
  - simpletest
  - restui
  - devel
  - search_api_solr
  - facets
  - content_browser
  - matomo
  - pdf
  - admin_toolbar
  - config_split
  - clamav
  - features
  - admin_toolbar_tools
  - transliterate_filenames
  - workbench
  - content_moderation
  - webform
  - schema_metatag
  - jsonapi
  - superfish
  - simple_sitemap
  - migrate_file
  - smtp
  - repo_bento_search
drupal_trusted_hosts:
  - ^localhost$
  - "{{ hostvars[groups['webserver'][0]].ansible_host }}"
  - ^repository.lib.asu.edu$
  - ^islandora-landing-elb-830028885.us-west-2.elb.amazonaws.com$
  - 10.192.17.204
drupal_trusted_hosts_file: "{{ drupal_core_path }}/sites/default/settings.php"
drupal_public_filesystem: "{{ drupal_core_path }}/sites/default/files"
drupal_external_libraries_directory: "{{ drupal_core_path }}/libraries"
drupal_jsonld_remove_format: true
