- name: Copy database backup script
  template:
    src: "webdb_backups.sh.j2"
    dest: "/home/ubuntu/webdb_backups.sh"
    owner: ubuntu
    group: ubuntu
    mode: '0744'

- name: Set up cron task
  cron:
    name: "database backups"
    job: "/home/ubuntu/webdb_backups.sh"
    hour: 4
    minute: 30
    user: ubuntu
  become: True
  when: inventory_dir is regex("stage|prod|aws")
