- name: Set clamav scan to daemon mode over unix socket
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y config:set clamav.settings scan_mode 2"
  args:
    chdir: /var/www/html/drupal/web


- name: Set path for clamav for unix socket
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y config:set clamav.settings mode_daemon_unixsocket.unixsocket /var/run/clamav/clamd.ctl"
  args:
    chdir: /var/www/html/drupal/web


- name: Disable CSS agg
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y config:set system.performance css.preprocess 0"
  args:
    chdir: /var/www/html/drupal/web


- name: Disable JS agg
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y config:set system.performance js.preprocess 0"
  args:
    chdir: /var/www/html/drupal/web


# - name: Install asu_metadata
#   command: "{{ drush_path }} --root {{ drupal_core_path }} -y en asu_metadata"
#   args:
#     chdir: /var/www/html/drupal/web

- name: Install islandora_search
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y en islandora_search"
  args:
    chdir: /var/www/html/drupal/web

- name: set the UUID of the site so that the configuration system doesn't complain
  command: '{{ drush_path }} --root {{ drupal_core_path }} config-set "system.site" uuid "9d8a3b2c-7a53-47f0-a53c-10dda41daf28"'
  args:
    chdir: /var/www/html/drupal/web
# drush config:import ?

# - name: set the gemini_url in the islandora settings
#   command: '{{ drush_path }} --root {{ drupal_core_path }} config-set "islandora.settings" gemini_url "http://localhost:8000/gemini"'

# - name: select the bundle types to display the fedora URL by default
#   command: '{{ drush_path }} --root {{ drupal_core_path }} config-set "islandora.settings" '
