- name: Set clamav scan to daemon mode over unix socket
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y config:set clamav.settings scan_mode 2"
  args:
    chdir: /var/www/html/drupal/web
  when: inventory_dir is regex("stage|prod|aws")



- name: Set path for clamav for unix socket
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y config:set clamav.settings mode_daemon_unixsocket.unixsocket /var/run/clamav/clamd.ctl"
  args:
    chdir: /var/www/html/drupal/web
  when: inventory_dir is regex("stage|prod|aws")


- name: Disable CSS agg
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y config:set system.performance css.preprocess 0"
  args:
    chdir: /var/www/html/drupal/web


- name: Disable JS agg
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y config:set system.performance js.preprocess 0"
  args:
    chdir: /var/www/html/drupal/web


# - name: Install asu_metadata
#   command: "{{ drush_path }} --root {{ drupal_core_path }} -y en asu_metadata"
#   args:
#     chdir: /var/www/html/drupal/web

- name: Install islandora_search
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y en islandora_search"
  args:
    chdir: /var/www/html/drupal/web

- name: set the UUID of the site so that the configuration system doesn't complain
  command: '{{ drush_path }} --root {{ drupal_core_path }} config-set "system.site" uuid "9d8a3b2c-7a53-47f0-a53c-10dda41daf28"'
  args:
    chdir: /var/www/html/drupal/web
# drush config:import ?

# - name: set the gemini_url in the islandora settings
#   command: '{{ drush_path }} --root {{ drupal_core_path }} config-set "islandora.settings" gemini_url "http://localhost:8000/gemini"'

# - name: select the bundle types to display the fedora URL by default
#   command: '{{ drush_path }} --root {{ drupal_core_path }} config-set "islandora.settings" '

- name: enable asu_taxonomies module
  command: '{{ drush_path }} --root {{drupal_core_path}} pm-enable asu_taxonomies'
  args:
    chdir: /var/www/html/drupal/web

- name: run asu_taxonomies migrations
  command: '{{ drush_path }} --root {{drupal_core_path}} migrate:import --group asu_taxonomies'
  args:
    chdir: /var/www/html/drupal/web

- name: set smtp access key from the vault
  when: inventory_dir is regex("stage|prod|aws")
  command: '{{ drush_path }} --root {{drupal_core_path}} config:set smtp.settings smtp_username {{aws_smtp_access_key}}'
  args:
    chdir: /var/www/html/drupal/web


- name: set smtp password from the vault
  when: inventory_dir is regex("stage|prod|aws")
  command: '{{ drush_path }} --root {{drupal_core_path}} config:set smtp.settings smtp_password {{aws_smtp_secret_key}}'
  args:
    chdir: /var/www/html/drupal/web

- name: Edit Drupal's Setting file for aws s3
  when: inventory_dir is regex("stage|prod|aws")
  lineinfile:
    path: "/var/www/html/drupal/web/sites/default/settings.php"
    line: "$settings['s3fs.access_key'] = '{{ aws_s3_access_key }}';"

- name: Edit Drupal's Setting file for aws s3
  when: inventory_dir is regex("stage|prod|aws")
  lineinfile:
    path: "/var/www/html/drupal/web/sites/default/settings.php"
    line: "$settings['s3fs.secret_key'] = '{{ aws_s3_secret_key }}';"

- name: Edit Drupal's Setting file for aws s3
  when: inventory_dir is regex("stage|prod|aws")
  lineinfile:
    path: "/var/www/html/drupal/web/sites/default/settings.php"
    line: "$settings['s3fs.use_s3_for_private'] = TRUE;"

- name: Edit Drupal's Setting file for aws s3
  when: inventory_dir is regex("stage|prod|aws")
  lineinfile:
    path: "/var/www/html/drupal/web/sites/default/settings.php"
    line: "$settings['s3fs.use_s3_for_public'] = TRUE;"

- name: remove changelog.txt for path-based vulnerability
  ansible.builtin.file:
    src: /var/www/html/drupal/web/core/CHANGELOG.txt
    state: absent

# TODO
# add the password for LDAP from the yml
# $settings['ldap_servers.server.asu_ldap']['bindpw'] = '';
